# Generated by Django 3.1.7 on 2021-03-19 04:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('name', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='fullname',
            new_name='Fullname',
        ),
    ]
