# Generated by Django 3.1.7 on 2021-04-04 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('name', '0002_auto_20210319_0958'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog_post',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('content', models.CharField(max_length=5000)),
                ('image', models.ImageField(upload_to='static')),
                ('slug', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=100)),
                ('post_date', models.DateTimeField(blank=True)),
            ],
        ),
    ]
