# Generated by Django 3.1.7 on 2021-04-25 03:55

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('name', '0005_comment_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog_post',
            name='content',
            field=tinymce.models.HTMLField(),
        ),
    ]
